# Generated by Django 5.1.1 on 2024-10-03 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='address',
        ),
        migrations.RemoveField(
            model_name='record',
            name='city',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='record',
            name='date_borrowed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='record',
            name='date_returned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
